# Generated by Django 4.1.1 on 2022-09-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ordered_reserved_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_for', to='catalog.client'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='ordered_reserved_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_by', to='catalog.manager'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='reserved_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_for', to='catalog.client'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='reserved_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_by', to='catalog.manager'),
        ),
    ]
