# Generated by Django 4.1.1 on 2022-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_ordered_reserved_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='customs_tax',
            field=models.IntegerField(default=1.5, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='hs_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='margin_coefficient',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='transport_coefficient',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
