# Generated by Django 4.1.1 on 2022-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_description_alter_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
