# Generated by Django 4.1.1 on 2022-09-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_catalog_image_userprofile_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Clients_info',
        ),
    ]
