# Generated by Django 4.1.1 on 2022-09-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_clients_clients_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='ordered_free',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='ordered_qty',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='ordered_reserved',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='ordered_reserved_client',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='ordered_reserved_manager',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='reserved_client',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='reserved_manager',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='reserved_qty',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='status',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Утвержден', 'Утвержден'), ('Желтые ботинки', 'Желтые ботинки')], default='В ожидании', max_length=25)),
                ('deal_sum', models.IntegerField()),
                ('received', models.IntegerField()),
                ('shipped', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.client')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manager')),
            ],
        ),
    ]
