# Generated by Django 4.1.1 on 2022-09-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cat'),
        ),
    ]
