# Generated by Django 4.1.1 on 2022-09-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_catalog_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='category',
        ),
    ]
