# Generated by Django 4.1.1 on 2022-09-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_cat_category_rename_cat_catalog_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
