# Generated by Django 4.1.1 on 2022-10-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_info',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='catalog.client'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('не заказано', 'не заказано'), ('заказано', 'заказано'), ('не оплачено', 'не оплачено'), ('предоплачено', 'предоплачено'), ('оплачено', 'оплачено')], max_length=15)),
                ('deal_sum', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('received', models.IntegerField()),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('proforma', models.CharField(blank=True, max_length=15)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.userprofile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='catalog.catalog')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Brands_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='catalog.brand')),
            ],
        ),
    ]
