# Generated by Django 4.1.1 on 2022-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_purchase_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, related_name='orders', to='catalog.catalog'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(null=True, related_name='purchases', to='catalog.catalog'),
        ),
    ]
