# Generated by Django 4.1.1 on 2022-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_order_product_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', to='catalog.catalog'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(related_name='purchases', to='catalog.catalog'),
        ),
    ]
