# Generated by Django 4.1.1 on 2022-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='max_sell_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='min_sell_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='orders',
            field=models.ManyToManyField(to='catalog.order'),
        ),
    ]
