# Generated by Django 4.1.1 on 2022-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_catalog_max_sell_price_catalog_min_sell_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deal_sum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
