# Generated by Django 4.1.1 on 2022-10-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_order_deal_sum_remove_order_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.IntegerField(default=0)),
                ('shipped', models.IntegerField(default=0)),
                ('not_shipped', models.IntegerField()),
                ('deal_sum', models.IntegerField()),
                ('received', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalog')),
            ],
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='orders',
        ),
        migrations.AddField(
            model_name='catalog',
            name='orders',
            field=models.ManyToManyField(through='catalog.Details', to='catalog.order'),
        ),
    ]
