# Generated by Django 4.1.1 on 2022-10-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_catalog_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalog.order'),
        ),
    ]
