# Generated by Django 4.1.1 on 2022-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_details_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='files',
            field=models.FileField(null=True, upload_to='static/files'),
        ),
    ]
