# Generated by Django 4.1.1 on 2022-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_details_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deal_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.FileField(null=True, upload_to='static/files'),
        ),
        migrations.AddField(
            model_name='order',
            name='not_shipped',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='catalog.order'),
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='orders',
        ),
        migrations.AddField(
            model_name='catalog',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='catalog.order'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
