# Generated by Django 4.1.1 on 2022-10-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_rename_product_orderproduct_item_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderItem',
        ),
    ]
