# Generated by Django 4.1.1 on 2022-10-17 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deal_sum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='not_shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='currency',
            field=models.CharField(choices=[('тг', 'тг'), ('евро', 'евро'), ('$', '$')], default='тг', max_length=10),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(related_name='order_items', to='catalog.orderitem')),
            ],
        ),
    ]
