# Generated by Django 4.1.1 on 2022-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_remove_order_deal_sum_remove_order_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart_items', to='catalog.orderitem'),
        ),
    ]
