# Generated by Django 4.1.1 on 2022-10-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.userprofile'),
        ),
    ]
