# Generated by Django 4.1.1 on 2022-10-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_cart_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='catalog',
            name='customs_tax',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='margin_coefficient',
            field=models.FloatField(default=1.3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='transport_coefficient',
            field=models.FloatField(default=1.1, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='zone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project'),
        ),
    ]
