# Generated by Django 4.1.1 on 2022-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_order_discount_order_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0.9),
        ),
    ]
