# Generated by Django 4.1.1 on 2022-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_orderitem_discount_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='currency',
            field=models.CharField(choices=[('тг', 'тг'), ('евро', 'евро'), ('долларов', 'долларов')], default='тг', max_length=10),
        ),
    ]
