# Generated by Django 4.1.1 on 2022-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_alter_order_discount_alter_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.IntegerField(default=0),
        ),
    ]
