# Generated by Django 4.1.1 on 2022-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_alter_orderitem_item_ordereditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_items', to='catalog.ordereditem'),
        ),
    ]
