# Generated by Django 4.1.1 on 2022-10-26 10:06

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_catalog_max_sell_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='currency',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='max_sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='min_sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3),
        ),
    ]
