# Generated by Django 4.1.1 on 2022-10-26 10:14

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_remove_catalog_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
    ]
