# Generated by Django 4.1.2 on 2022-10-27 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_order_received_currency_alter_order_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='deal_sum',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.organisation'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.organisation'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purhases', to='catalog.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='purchase_items', to='catalog.purchaseditem'),
        ),
    ]
