# Generated by Django 4.1.2 on 2022-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_remove_purchase_deal_sum_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('не заказано', 'не заказано'), ('не оплачено', 'не оплачено'), ('предоплачено', 'предоплачено'), ('оплачено', 'оплачено')], max_length=15),
        ),
    ]
