# Generated by Django 4.1.2 on 2022-10-27 12:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_alter_purchase_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='purchase_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KZT', max_digits=14),
        ),
    ]
