# Generated by Django 4.1.2 on 2022-10-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_catalog_purchase_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='catalog.catalog'),
        ),
    ]
