# Generated by Django 4.1.2 on 2022-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0069_alter_catalog_zone_alter_purchaseditem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='purchase_items', to='catalog.purchaseditem'),
        ),
    ]
