# Generated by Django 4.1.2 on 2022-10-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
