# Generated by Django 4.1.2 on 2022-11-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_brand_bank_acc_brand_bik_client_bank_acc_client_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.subcategory'),
        ),
    ]
