# Generated by Django 4.1.2 on 2022-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_alter_brand_contact_person_alter_brand_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
