# Generated by Django 4.1.2 on 2022-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_catalog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='barcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='external_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
