# Generated by Django 4.1.2 on 2022-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_catalog_barcode_catalog_code_catalog_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='model',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
