# Generated by Django 4.1.2 on 2022-11-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_alter_catalog_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='stock_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
