# Generated by Django 4.1.2 on 2022-11-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_alter_catalog_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
