# Generated by Django 4.1.2 on 2022-11-30 01:31

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_alter_brand_phone_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='article',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='hs_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='margin_coefficient',
            field=models.FloatField(blank=True, default=1.3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='max_sell_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='min_sell_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='purchase_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='KZT', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('KZT', 'KZT ₸'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='KZT', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='transport_coefficient',
            field=models.FloatField(blank=True, default=1.1, null=True),
        ),
    ]
