# Generated by Django 4.1.2 on 2022-11-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_alter_catalog_article_alter_catalog_hs_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
