# Generated by Django 4.1.2 on 2022-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_alter_catalog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
